{{- if .Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallet-data
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.class }}
{{- end }}